# Generated by Django 4.0.1 on 2022-06-30 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exibicao', models.CharField(max_length=100)),
                ('eh_lider', models.BooleanField(default=False)),
                ('eh_diretor', models.BooleanField(default=False)),
                ('area', models.CharField(choices=[('F', 'Financeiro'), ('GP', 'Gestão de Pessoas'), ('P', 'Gestão de Projetos'), ('M', 'Marketing')], max_length=2, null=True)),
                ('projeto', models.CharField(choices=[('AMBI', 'Ambientar'), ('INFO', 'Informar'), ('PONT', 'Pontuais'), ('CA10', 'Camisa 10'), ('AULA', 'Aulas Solidárias'), ('CHAL', 'Challenge'), ('MUND', 'Mun'), ('SOMA', 'Somar'), ('SOCI', 'Social Planning'), ('VENU', 'Vênus'), ('ALEG', 'Alegrarte')], max_length=4, null=True)),
                ('pontos', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
