# Generated by Django 4.0.1 on 2022-07-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='area',
            field=models.CharField(blank=True, choices=[('F', 'Financeiro'), ('GP', 'Gestão de Pessoas'), ('P', 'Gestão de Projetos'), ('M', 'Marketing')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='projeto',
            field=models.CharField(blank=True, choices=[('AMBI', 'Ambientar'), ('INFO', 'Informar'), ('PONT', 'Pontuais'), ('CA10', 'Camisa 10'), ('AULA', 'Aulas Solidárias'), ('CHAL', 'Challenge'), ('MUND', 'Mun'), ('SOMA', 'Somar'), ('SOCI', 'Social Planning'), ('VENU', 'Vênus'), ('ALEG', 'Alegrarte')], max_length=4, null=True),
        ),
    ]
