# Generated by Django 4.0.1 on 2022-07-31 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_perfil_area_alter_perfil_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='projeto',
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(choices=[('AMBI', 'Ambientar'), ('INFO', 'Informar'), ('PONT', 'Pontuais'), ('CA10', 'Camisa 10'), ('AULA', 'Aulas Solidárias'), ('CHAL', 'Challenge'), ('MUND', 'Mun'), ('SOMA', 'Somar'), ('SOCI', 'Social Planning'), ('VENU', 'Vênus'), ('ALEG', 'Alegrarte')], max_length=4)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='projetos',
            field=models.ManyToManyField(blank=True, to='api.Projetos'),
        ),
    ]
