# Generated by Django 4.0.1 on 2022-07-31 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_perfil_projeto_projetos_perfil_projetos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='projetos',
            new_name='projeto',
        ),
    ]
