# Generated by Django 4.0.1 on 2022-07-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_perfil_area_alter_perfil_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nome_exibicao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
